In [7]:
import torch
import convert_bcsr_ext

a = torch.tensor([
    [1, 2, 0, 4],
    [0, 0, 0, 0],
    [9, 0, 0, 12],
    [13, 0, 0, 16],
], dtype=torch.float32, device='cuda')
mask = torch.tensor([
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 1, 1, 1],
    [0, 0, 0, 0],
], dtype=torch.int32, device='cuda')

bcsr = convert_bcsr_ext.forward(mask, a, 1, 4)
bcsr


[tensor([0, 1, 2, 3, 4], device='cuda:0', dtype=torch.int32),
 tensor([0, 0, 0, 0], device='cuda:0', dtype=torch.int32),
 tensor([0, 1, 2, 3], device='cuda:0', dtype=torch.int32),
 tensor([[ 1.,  2.,  0.,  4.],
         [ 0.,  0.,  0.,  0.],
         [ 9.,  0.,  0., 12.],
         [13.,  0.,  0., 16.]], device='cuda:0'),
 tensor([0, 1, 2, 3], device='cuda:0', dtype=torch.int32)]